(require :asdf)
(asdf:load-system :ariadne)
(in-package :ariadne)
(let ((g (make-graph :name "test")))
  (import-turtle g (with-open-file (s "test-data/shacl/data-shapes/data-shapes-test-suite/tests/sparql/node/sparql-001.ttl" :external-format :utf-8)
                     (let ((b (make-string (file-length s)))) (read-sequence b s) b)))
  (let* ((focus "http://datashapes.org/sh/tests/sparql/node/sparql-001.test#InvalidResource1")
         (query (format nil "SELECT ?path ?value WHERE { <~A> ?path ?value . FILTER (?path = <http://www.w3.org/2000/01/rdf-schema#label>) }" focus)))
    (format t "Query: ~A~%" query)
    (handler-case
        (format t "Results: ~S~%" (sparql g query))
      (error (e) (format t "ERROR: ~A~%" e)))))
