(require :asdf)
(asdf:load-system :ariadne)
(in-package :ariadne)
(let ((g (make-graph :name "test")))
  (import-turtle g (with-open-file (s "test-data/shacl/data-shapes/data-shapes-test-suite/tests/sparql/node/sparql-001.ttl" :external-format :utf-8)
                     (let ((b (make-string (file-length s)))) (read-sequence b s) b)))
  (let* ((sc "http://datashapes.org/sh/tests/sparql/node/sparql-001.test#TestShape-sparql")
         (focus "http://datashapes.org/sh/tests/sparql/node/sparql-001.test#InvalidResource1")
         (sel (prop-shape-value g sc "select"))
         (clean (remove #\Return sel))
         (where-pos (search "WHERE" (string-upcase clean)))
         (select-part (subseq clean 0 where-pos))
         (where-part (subseq clean where-pos))
         (fixed-sel (cl-ppcre:regex-replace-all "\\$this" select-part "?__shacl_this"))
         (fixed-where (cl-ppcre:regex-replace-all "\\$this" where-part (format nil "<~A>" focus)))
         (fixed (concatenate 'string fixed-sel fixed-where)))
    (format t "QUERY:~%~A~%~%" fixed)
    (handler-case
        (format t "RESULTS: ~S~%" (sparql g fixed))
      (error (e) (format t "ERROR: ~A~%" e)))))
