(require :asdf)
(asdf:load-system :ariadne)
(in-package :ariadne)
;; Load shapes only
(let ((g1 (make-graph :name "shapes-only")))
  (import-turtle g1 (with-open-file (s "test-data/shacl/data-shapes/data-shapes-test-suite/tests/core/complex/shacl-shacl-data-shapes.ttl")
                      (let ((b (make-string (file-length s)))) (read-sequence b s) b)))
  (format t "Shapes only: ~A triples~%" (triple-count g1))
  (format t "  _:anon2 triples: ~A~%" (length (get-triples g1 :subject "_:anon2"))))
;; Load manifest then shapes
(let ((g2 (make-graph :name "both")))
  (import-turtle g2 (with-open-file (s "test-data/shacl/data-shapes/data-shapes-test-suite/tests/core/complex/shacl-shacl.ttl")
                      (let ((b (make-string (file-length s)))) (read-sequence b s) b)))
  (format t "After manifest: ~A triples~%" (triple-count g2))
  (format t "  _:anon2 triples: ~A~%" (length (get-triples g2 :subject "_:anon2")))
  (import-turtle g2 (with-open-file (s "test-data/shacl/data-shapes/data-shapes-test-suite/tests/core/complex/shacl-shacl-data-shapes.ttl")
                      (let ((b (make-string (file-length s)))) (read-sequence b s) b)))
  (format t "After both: ~A triples~%" (triple-count g2))
  (format t "  _:anon2 triples: ~A~%" (length (get-triples g2 :subject "_:anon2")))
  (dolist (tr (get-triples g2 :subject "_:anon2"))
    (format t "    ~S ~S~%" (triple-predicate tr) (triple-object tr))))
