(require :asdf)
(asdf:load-system :ariadne)
(in-package :ariadne)
(handler-case
    (let ((g (make-graph :name "test")))
      (import-turtle g (with-open-file (s "test-data/shacl/data-shapes/data-shapes-test-suite/tests/core/node/and-001.ttl")
                         (let ((b (make-string (file-length s)))) (read-sequence b s) b)))
      (format t "Triples: ~A~%" (triple-count g))
      (let ((report (shacl-validate g)))
        (format t "Conforms: ~A~%" (getf report :conforms))
        (format t "Results: ~A~%" (length (getf report :results)))))
  (error (e) (format t "ERROR: ~A~%" e)))
