(require :asdf)
(asdf:load-system :ariadne-tests)
(in-package :ariadne/tests)

(defvar *earl-results* nil)

(defun run-earl-test (file subdir)
  "Run a single test and record EARL result."
  (let ((name (pathname-name file)))
    (unless (or (string= "manifest" name)
                (and (> (length name) 5) (string= "-data" (subseq name (- (length name) 5))))
                (and (> (length name) 7) (string= "-shapes" (subseq name (- (length name) 7)))))
      (handler-case
          (multiple-value-bind (ok expected actual) (run-shacl-w3c-test file)
            (let* ((test-path (format nil "~A~A" subdir name))
                   (outcome (cond
                              ((eq expected :error) "earl:passed")
                              (ok "earl:passed")
                              (t "earl:failed"))))
              (push (cons test-path outcome) *earl-results*)))
        (error (e) (format t "ERROR on ~A: ~A~%" name e))))))

(dolist (subdir '("complex/" "misc/" "node/" "property/" "path/" "targets/" "validation-reports/"))
  (let ((dir (merge-pathnames subdir *shacl-test-base*)))
    (when (probe-file dir)
      (dolist (file (sort (directory (merge-pathnames "*.ttl" dir)) #'string< :key #'namestring))
        (run-earl-test file (format nil "core/~A" subdir))))))

(dolist (subdir '("component/" "node/" "property/" "pre-binding/"))
  (let ((dir (merge-pathnames (concatenate 'string "../sparql/" subdir) *shacl-test-base*)))
    (when (probe-file dir)
      (dolist (file (sort (directory (merge-pathnames "*.ttl" dir)) #'string< :key #'namestring))
        (run-earl-test file (format nil "sparql/~A" subdir))))))

;; Generate EARL report
(let ((results (nreverse *earl-results*)))
  (with-open-file (s "ariadne-shacl-earl.ttl" :direction :output :if-exists :supersede)
  (format s "# baseURI: https://sr.ht/~~hajovonta/ariadne/earl~%~%")
  (format s "@prefix doap: <http://usefulinc.com/ns/doap#> .~%")
  (format s "@prefix earl: <http://www.w3.org/ns/earl#> .~%")
  (format s "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .~%")
  (format s "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .~%")
  (format s "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .~%~%")
  (format s "<https://sr.ht/~~hajovonta/ariadne>~%")
  (format s "  rdf:type doap:Project ;~%")
  (format s "  rdf:type earl:Software ;~%")
  (format s "  rdf:type earl:TestSubject ;~%")
  (format s "  doap:name \"Ariadne\" ;~%")
  (format s "  doap:description \"Graph database in Common Lisp\" ;~%")
  (format s "  doap:programming-language \"Common Lisp\" ;~%")
  (format s "  doap:homepage <https://sr.ht/~~hajovonta/ariadne> ;~%")
  (format s ".~%")
  (dolist (result results)
    (format s "[~%")
    (format s "  rdf:type earl:Assertion ;~%")
    (format s "  earl:assertedBy <https://sr.ht/~~hajovonta> ;~%")
    (format s "  earl:result [~%")
    (format s "      rdf:type earl:TestResult ;~%")
    (format s "      earl:mode earl:automatic ;~%")
    (format s "      earl:outcome ~A ;~%" (cdr result))
    (format s "    ] ;~%")
    (format s "  earl:subject <https://sr.ht/~~hajovonta/ariadne> ;~%")
    (format s "  earl:test <urn:x-shacl-test:/~A> ;~%" (car result))
    (format s "].~%")))

(format t "Generated ariadne-shacl-earl.ttl with ~A test results~%" (length results)))
