(require :asdf)
(asdf:load-system :ariadne-tests)
(in-package :ariadne/tests)
(dolist (subdir '("component/" "node/" "property/" "pre-binding/"))
  (let ((dir (merge-pathnames (concatenate 'string "../sparql/" subdir)
                              *shacl-test-base*)))
    (when (probe-file dir)
      (format t "~%=== sparql/~A ===~%" subdir)
      (let ((pass 0) (fail 0) (err 0))
        (dolist (file (sort (directory (merge-pathnames "*.ttl" dir)) #'string< :key #'namestring))
          (let ((name (pathname-name file)))
            (unless (or (string= "manifest" name)
                        (and (> (length name) 5) (string= "-data" (subseq name (- (length name) 5))))
                        (and (> (length name) 7) (string= "-shapes" (subseq name (- (length name) 7)))))
              (multiple-value-bind (ok expected actual) (run-shacl-w3c-test file)
                (cond
                  ((eq expected :error) (incf err) (format t "  ERROR ~A~%" name))
                  (ok (incf pass))
                  (t (incf fail) (format t "  FAIL  ~A (expected ~A got ~A)~%" name expected actual)))))))
        (format t "  ~A pass, ~A fail, ~A errors~%" pass fail err)))))
